name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger action when pushing to the master branch (or 'main')

jobs:
  build:
    runs-on: ubuntu-latest  # Can be windows if you must use it

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages (using peaceiris action)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # The directory to deploy
