name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger action when pushing to the master branch (or 'main')

jobs:
  build:
    runs-on: windows-latest  # Use Windows environment for CI/CD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out the repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set Node.js version to 16

      - name: Cache npm dependencies (Optional)
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install  # Install the dependencies

      - name: Build the project
        run: npm run build  # Build the project

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4  # Deploy to GitHub Pages
        with:
          branch: gh-pages  # Deployment branch
          folder: dist  # Folder with built assets
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for deployment
